### ISSUE TITLE
Column names in viewed output from `avail.pts`

### ISSUE THREAD

**Issue by jcarlis3** [jcarlis3/ecoinfo#1]
If I call the `avail.pts` function and assign the output to an object called "abs",

![image](https://cloud.githubusercontent.com/assets/10441106/12310880/45f656b6-ba10-11e5-8be3-d946667a974f.png)

 then run `View(abs)`, there's a weird thing happening where the column of x coordinates is being named "abs".

![image](https://cloud.githubusercontent.com/assets/10441106/12310777/5cbe1858-ba0f-11e5-90b9-e717625c406d.png)

However, examining the `data` and `coords` slots of `abs` reveals no issue.

![image](https://cloud.githubusercontent.com/assets/10441106/12310837/dfd8f74e-ba0f-11e5-9606-891c0482f7b6.png)

**Comment by salbeke** [comment]
I’ve seen this happen in other R sessions. Has to be something with R Studio. Nothing to worry about since the attribute table has nothing changing, merely a view of the data with the added xy.
